config/routes.rb
Urbannomadfilmfest::Application.routes.draw do

  scope "(:locale)/", :locale => /zh\_TW|en/ do
  	resources :briefs
  	
  	resources :categories, :except => [:new, :edit, :destroy] do
		resources :briefs, :only => [:show, :index]
	end

  	
	match "/admin/createAdmin" => "admin#createAdmin", :via => :post
	match "/admin/loginCheck" => "admin#loginCheck", :via => :post
	match "/admin/update" => "admin#update", :via => :put
	
	namespace :admin do
		get '/' => 'categories#index'    
		get "sign_up", "log_in", "log_out", "edit"
		
		match 'showAdmins' => 'admin#showAdmins' 
		
		resources :categories, :except => [:new, :edit, :destroy] do
			resources :briefs, :except => :new do
			  match 'uploadPhoto' => 'briefs#createPhoto', :via => [:post]
			  match 'deletePhoto/:id' => 'briefs#destroyPhoto', :via => [:delete]
			end
		end
	end
	
	match "pages/:page"		=> "static_page#show"
	
	
	root :to => "static_page#index"
  	
  end

end

app/models/brief.rb
class Brief < ActiveRecord::Base
  has_many :brief_photos
  belongs_to :category
  attr_accessible :content, :name, :en_name, :new_create, :status, :cover, :intro, :date, :inner_photo, :schedule
  
  serialize :schedule
  
  mount_uploader :cover, MovieCoverUploader
  mount_uploader :inner_photo, InnerPhotoUploader
  
  translates :content, :intro, :fallbacks_for_empty_translations => true
  
  before_save :fill_empty_date
  
  def fill_empty_date
  
  	if self.date.nil?
  		self.date = Time.now
  	end
  
  end
  
end

app/controllers/admin/briefs_controller.rb
class Admin::BriefsController < ApplicationController
  before_filter :require_is_admin
  before_filter :get_category
  
  layout 'admin'
  def index
  	@categories = Category.all
  	
    @briefs = @category.briefs.order('date DESC').page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brief }
    end
  end

  # GET /brief/1
  # GET /brief/1.json
  def show
    @brief = Brief.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brief }
    end
  end

  # GET /brief/1/edit
  def edit
    @brief = Brief.find(params[:id])
    @photo = BriefPhoto.new
  end

  #create photo
  def createPhoto
    @brief = Brief.find(params[:brief_id])
    @photo = @brief.brief_photos.new(params[:brief_photo])
    
    respond_to do |format|
      if @photo.save
        #format.html { redirect_to photos.path } #index.html.erb
        format.json { render json: @photo, status: :created, location: @photo }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end
  
  def destroyPhoto
    @photo = BriefPhoto.find(params[:id])
    #File.delete("/public" + @photo.image) #carrierwave will handle this.
    @photo.destroy

    respond_to do |format|
          #format.html { redirect_to :controller => 'photos', :action => 'index' }
          format.js
          format.json { head :no_content }
      end
  end

  # POST /brief
  # POST /brief.json
  def create
    @brief = @category.briefs.build(params[:brief])
    @brief.new_create = true

    respond_to do |format|
      if @brief.save
        format.html { redirect_to edit_admin_category_brief_path(@category, @brief, :locale => I18n.locale), notice: 'Brief was successfully created.' }
        format.json { render json: @brief, status: :created, location: @brief }
      else
        format.html { render action: "new" }
        format.json { render json: @brief.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brief/1
  # PUT /brief/1.json
  def update
    @brief = Brief.find(params[:id])

    respond_to do |format|
      if @brief.update_attributes(params[:brief])
        format.html { redirect_to admin_category_brief_path(@category, @brief, :locale => I18n.locale), notice: 'Brief was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brief.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brief/1
  # DELETE /brief/1.json
  def destroy
    @brief = Brief.find(params[:id])
    @brief.destroy

    respond_to do |format|
      format.html { redirect_to admin_category_briefs_path( @category ) }
      format.json { head :no_content }
    end
  end
  
private
  def get_category
  	@category = Category.where( "id = '#{params[ :category_id ]}' OR namehash = '#{params[ :category_id ]}'" ).first
  end
  
end

app/controllers/briefs_controller.rb
class BriefsController < ApplicationController
  before_filter :get_category

 def index
 	@briefs = @category.briefs.order( 'date DESC' )
 end

  # GET /briefs/1
  # GET /briefs/1.json
  def show
    @brief = Brief.find(params[:id])
    seek_flag = false    
    
    @briefs = @category.briefs.where( :status => "enable" ).order( "date DESC" )
    
    @briefs.each do | br |
    	@next = br
    	@prev = br if @prev.nil?    	
    	
    	if br.id == @brief.id
	    	seek_flag = true
	    	next
    	end
    	
    	break if seek_flag
    	
    	@prev = br
    	
    end
    
    @next = @briefs.first if @next.id == @brief.id
    @prev = @briefs.last if @prev.id == @brief.id
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brief }
    end
  end
  
private
  def get_category
  	@category = Category.where( "id = '#{params[ :category_id ]}' OR namehash = '#{params[ :category_id ]}'" ).first
  end
  
end

app/helpers/briefs_helper.rb
module BriefsHelper
end

app/views/briefs/index.html.erb
	<%= stylesheet_link_tag "index", :media => "all" %>
	
  	<% @briefs.each do | brief | 
	  	next if brief.status != 'enable'
	  	Rails.logger.debug " **** Entering debug **** "
	  	Rails.logger.debug brief.inspect
	  	Rails.logger.debug " **** End **** "
  	%>  		
	    <div class="movie">
	    <a href="<%= category_brief_path(:category_id => brief.category.namehash, :id => brief.id, :locale => I18n.locale ) %>">
	      <div class="post"><img src="<%= brief.cover.thumb %>" width="207" height="304"></div>
	      <!--post-->
	      <div class="info">
	        <hgroup>
	          <h3><%= brief.name %></h3>
	          <h4><%= brief.en_name %></h4>
	        </hgroup>
	        <% if !brief.intro.nil? %>
	        <p> 
	        	<%= brief.intro.sub(/\n/, '<br>').html_safe %> 
	        </p>
	        <% end %>
	        
	        <% if !brief.schedule.nil? %>
	        <p class="time">
	        <% brief.schedule.each do | schedule | %>
	        	<%= schedule  %><br />
	        <% end %>
	        </p>
	        <% end %>
	      </div>
	      <!--info-->
	      </a> 
	    </div>
  	<% end %>
  
    <!--movie-->

app/views/briefs/show.html.erb
<%= stylesheet_link_tag "page", :media => "all" %>
<div id="turntable">
  <div class="prev"><a href="<%= category_brief_path( :category_id => @category.namehash, :id => @prev.id, :locale => I18n.locale ) %>"></a></div>
  <div class="post"><img src="<%= image_path(@brief.inner_photo.show) %>" width="540" height="359"></div>
  <div class="next"><a href="<%= category_brief_path( :category_id => @category.namehash, :id => @next.id, :locale => I18n.locale ) %>"></a></div>
</div>
<hgroup>
  <h3><%= @brief.name %></h3>
  <h4><%= @brief.en_name %></h4>
</hgroup>
<p><%= @brief.intro.sub(/\n/, "<br>").html_safe if !@brief.intro.nil? %> &nbsp;     </p>

<input id="brief_content" style="display:none;" type="text" value="<%=@brief.content%>">
<p id="articleContent"></p>



<script type="text/javascript">
$(document).ready(function() {
  $("#briefes").addClass("active");
  showContent();

  function showContent(){
    if($("#brief_content").val())
    {
      var obj = JSON.parse($("#brief_content").val());
      var article = "";
      for(i=0;i<obj.article.length;i++)
      {
        var paragraph = obj.article[i];

         if(JSON.stringify(paragraph.type)=='"paragraph"')
        {
          article = "<p class='"+paragraph.cssclass+"' '>";

          if(paragraph.link){
            article += "<a target='_blank' href='"+paragraph.link+"'>"+jsonReplace(JSON.stringify(paragraph.content)).replace(/\\n/g, "<br />")+"</a></p>";
          }
          else{
            article += jsonReplace(JSON.stringify(paragraph.content)).replace(/\\n/g, "<br />")+"</p>";
          }
        }
        else if(JSON.stringify(paragraph.type)=='"image"')
        {
          article = "<img alt=" + JSON.stringify(paragraph.id) + " src=" + JSON.stringify(paragraph.path) + " title=" + JSON.stringify(paragraph.id) + " />";
        }
        else if(JSON.stringify(paragraph.type)=='"linkedimg"')
        {
          article = "<a href="+JSON.stringify(paragraph.link)+" target='_blank'><img alt=" + JSON.stringify(paragraph.imgid) + " src=" + JSON.stringify(paragraph.imgpath) + " title=" + JSON.stringify(paragraph.imgid) + " /></a>";
        }
        else if (JSON.stringify(paragraph.type)=='"video"') {
          var sourceLink = getVideoSourceLink(paragraph.provider);      
          article = "<div  class='paragraphContainer' data-type='video' data-code=\"" + paragraph.code + "\"><iframe width=\"713\" height=\"401\" data-code=\"" + paragraph.code + "\" src=\"" + sourceLink + paragraph.code+ "\" frameborder=\"0\" allowfullscreen></iframe></div>";
        }
        $("#articleContent").append(article);
      }
    }
  }

  function jsonReplace(string){return string.replace(/"([^"]*)"/g, "$1");}
  
});

</script>