config/routes.rb
Urbannomadfilmfest::Application.routes.draw do

  scope "(:locale)/", :locale => /zh\_TW|en/ do
  	resources :briefs
  	
  	resources :categories, :except => [:new, :edit, :destroy] do
		resources :briefs, :only => [:show, :index]
	end

  	
	match "/admin/createAdmin" => "admin#createAdmin", :via => :post
	match "/admin/loginCheck" => "admin#loginCheck", :via => :post
	match "/admin/update" => "admin#update", :via => :put
	
	namespace :admin do
		get '/' => 'categories#index'    
		get "sign_up", "log_in", "log_out", "edit"
		
		match 'showAdmins' => 'admin#showAdmins' 
		
		resources :categories, :except => [:new, :edit, :destroy] do
			resources :briefs, :except => :new do
			  match 'uploadPhoto' => 'briefs#createPhoto', :via => [:post]
			  match 'deletePhoto/:id' => 'briefs#destroyPhoto', :via => [:delete]
			end
		end
	end
	
	match "pages/:page"		=> "static_page#show"
	
	
	root :to => "static_page#index"
  	
  end

end

app/views/layouts/_footer_en.erb
<footer>
<ul>
<li><a href="http://urbannomaden.blogspot.tw/" target="_blank">Home</a></li>
<li><a href="http://urbannomaden.blogspot.tw/p/about-us.html#news" target="_blank">About Us</a></li>
<li><a href="http://urbannomaden.blogspot.tw/p/submit-film.html#news" target="_blank">Submit a Film</a></li>
<li><a href="http://www.youtube.com/user/urbannomadfilmfest?feature=mhum" target="_blank">UNTV</a></li>	
<li><a href="http://urbannomaden.blogspot.tw/p/in-media.html" target="_blank">In the Media</a></li>
<li><a href="http://urbannomaden.blogspot.tw/p/contact-us.html#news" target="_blank">Contact Us</a></li>
<li><a href="http://urbannomadfilmfest.blogspot.tw/" target="_blank">中文</a></li>
</ul>
</footer>

app/views/layouts/_footer_zh.erb
<footer>
	<ul>
	<li><a href="http://urbannomadfilmfest.blogspot.tw/" target="_blank">首頁</a></li>
	<li><a href="http://urbannomadfilmfest.blogspot.tw/p/blog-page.html" target="_blank">關於我們</a></li>
	<li><a href="http://urbannomadfilmfest.blogspot.tw/p/blog-page_05.html#news" target="_blank">徵件</a></li>
	<li><a href="http://urbannomadfilmfest.blogspot.tw/p/blog-page_14.html" target="_blank">志工徵求</a></li>
	<li><a href="http://www.youtube.com/user/urbannomadfilmfest/featured" target="_blank">UNTV</a></li>	
	<li><a href="http://urbannomadfilmfest.blogspot.tw/p/blog-page_23.html" target="_blank">媒體報導</a></li>
	<li><a href="http://urbannomadfilmfest.blogspot.tw/p/blog-page_7019.html#news" target="_blank">聯絡</a></li>
	<li><a href="http://schedule.urbannomad.tw/englishsite" target="_blank">English</a></li>
	</ul>
</footer>

app/views/layouts/_menu.html.erb
<nav>
    <ul>
      <li><a href="<%= root_url %>" id="nav-home" class="ablock">home</a></li>
      <li><%= link_to "English", url_for( :locale => :en ), :class => "atext" %></li>
      <li><a class="atext">/</a></li>
      <li><%= link_to "中文", url_for( :locale => :zh_TW ), :class => "atext"  %></li>
      <li><a href="http://www.facebook.com/UrbanNomad.tw" target="_blank" id="nav-fb" class="ablock">
        <div class="flipper">
          <div class="front"> facebook </div>
          <div class="back"> </div>
        </div>
        </a></li>
      <li><a href="<%= category_briefs_path( :category_id => "talks", :locale => I18n.locale ) %>" id="nav-04" class="ablock">
        <div class="flipper">
          <div class="front"> <%= t("menu.talks") %> </div>
          <div class="back"> </div>
        </div>
        </a></li>
      <li><a href="<%= root_url + "/pages/schedule"  %>" id="nav-03" class="ablock">
        <div class="flipper">
          <div class="front"> <%= t("menu.schedule")%> </div>
          <div class="back"> </div>
        </div>
        </a></li>
      <li><a href="<%= category_briefs_path( :category_id => "short", :locale => I18n.locale ) %>" id="nav-02" class="ablock">
        <div class="flipper">
          <div class="front"> <%= t("menu.short_film")%> </div>
          <div class="back"> </div>
        </div>
        </a></li>
      <li><a href="<%= category_briefs_path( :category_id => "full", :locale => I18n.locale ) %>" id="nav-01" class="ablock">
        <div class="flipper">
          <div class="front"> <%= t("menu.features_film")%> </div>
          <div class="back"> </div>
        </div>
        </a></li>
    </ul>
  </nav>

app/views/layouts/_meta_en.erb
<meta name="keywords" content="2013, Film Fest, Taipei, Film, Introduction"/>
<meta property="og:site_name" content="2013 URBANNOMAD FILM FEST "/>

<meta name="description" content="2013 URBANNOMAD FILM FEST –Film and Activity Introductions "/>
<meta property="og:title" content="2013 URBANNOMAD FILM FEST –Film and Activity Introductions "/>
<meta property="og:description" content="2013 URBANNOMAD FILM FEST –Film and Activity Introductions "/>

<title>2013 URBANNOMAD FILM FEST –Film and Activity Introductions </title>

app/views/layouts/_meta_zh.erb
<meta property="og:site_name" content="2013 城市遊牧影展"/>

<meta name="keywords" content="2013, 影展, 台北, 時間表" />

<% if params[ :controller ] == "static_page" && params[ :action ]  == "index" %>

<!-- index meta -->
<meta name="description" content="2013 城市游牧影展-電影時間表，活動內容完整查詢。"/>
<meta property="og:title" content="2013 城市遊牧影展-電影時間表"/>
<meta property="og:description" content="2013 城市游牧影展-電影時間表，活動內容完整查詢。"/>

<% else %>

<meta name="description" content="2013 城市游牧影展-影展電影與影展活動完整介紹。"/>
<meta property="og:title" content="2013 城市遊牧影展-影展電影完整介紹"/>
<meta property="og:description" content="2013 城市游牧影展-影展電影與影展活動完整介紹。"/>

<% end %>

<title>2013 城市遊牧影展-影展電影完整介紹</title>

app/views/layouts/admin.html.erb
<!doctype html>
<html>
<head>
<!--[if lt IE 9]>
<script src="js/html5.js"></script>
<link rel="stylesheet" href="css/desktop.css">
<![endif]-->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" />
<meta name="Robots" content="index,follow"/>
<meta http-equiv="content-language" content="zh-TW" />
<title><%=t("admin.page_title")%></title>

<%= stylesheet_link_tag "reset", :media => "all" %>
<%= stylesheet_link_tag "admin", :media => "all" %>
<%= stylesheet_link_tag "alertify", :media => "all" %>
<%= stylesheet_link_tag "custom", :media => "all" %>

<link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />

<%= stylesheet_link_tag "adminRWD/mobile", :media => "screen and (max-width: 543px)" %>
<%= stylesheet_link_tag "adminRWD/tablet", :media => "screen and (min-width: 544px) and (max-width: 896px)" %>
<%= stylesheet_link_tag "adminRWD/desktop", :media => "screen and (min-width: 897px)" %>

<title><%= t("admin.page_title") %></title>

<%= javascript_include_tag "application", :media => "all" %>
<%= csrf_meta_tags %>

<script>
$(document).ready(function() {	
	$('#aside-ctrl').click(function(event) { 
   /* aside-box 顯示後,綁上點擊document中的物件隱藏 aside-box 的事件 */
    $('#aside-box').fadeIn(function(){
      $(document).click(function() {
        $('#aside-box').fadeOut();
        $(document).unbind();
      });
    });

    event.preventDefault();
	});  
	
  var isNavOpen = false;
	$('#nav-ctrl').click(function() {
    $('#nav-ctrl').unbind();
    showNav();
	});

  function showNav(){
    var leftPosition;

    switch(isNavOpen){
      case true:
        leftPosition = 0;
        break;
      case false:
        leftPosition = 150;
        break;
    }
    
    $('article').animate({ left: leftPosition }, 1000, 'easeOutQuad', function() {
      $('#nav-ctrl').click(function() {
        $('#nav-ctrl').unbind();
        showNav();
      });
    });

    isNavOpen = isNavOpen? false : true;
  }
});
</script>
<script>
$(function(){	
	var _showTab = 0;
	var $defaultLi = $('.tab li').eq(_showTab).addClass('active');
	$($defaultLi.find('a').attr('href')).siblings().hide();
 	$('.tab li').click(function() {		
		var $this = $(this),
			_clickTab = $this.find('a').attr('href');		
		$this.addClass('active').siblings('.active').removeClass('active');		
		$(_clickTab).stop(false, true).fadeIn().siblings().hide(); 
		return false;
		}).find('a').focus(function(){
			this.blur();
	});
});
</script>

<body>
<header _height="none">
  <section id="top"> <a id="nav-ctrl"><img src="<%= image_path("nav.png") %>"></a>
    <div id="lang"> 
    	<% if I18n.locale == :zh_TW %>
    	<%= link_to image_tag('tw.png') + ' 繁中', url_for( :locale => :zh_TW ) %>
    	<%= link_to image_tag('us.png') + 'English', url_for( :locale => :en ) %>
    	<% else %>
    	<%= link_to image_tag('us.png') + 'English', url_for( :locale => :en ) %>
    	<%= link_to image_tag('tw.png') + ' 繁中', url_for( :locale => :zh_TW ) %>
    	<% end %>
    </div>
    <h1><a href="#">遊牧影展後台管理系統</a></h1>
    <aside> <a id="aside-ctrl"><img src="<%= image_path("set.png") %>"></a>
      <div id="aside-box"> 
      <%if session[:admin]%>
      你好，<%= session[:admin]%>！<a href="/admin/edit">修改個人資料</a><a href="/admin/log_out">登出</a><a href="<%= root_url %>">返回首頁</a> 
      <% end %>
      </div>
    </aside>
  </section>
  <!--top--> 
</header>

<section id="main" _height="auto">
  <%if session[:admin]%>
  <nav>
    <ul>
      <li><a href="<%= admin_category_briefs_path( Category.first, :locale => I18n.locale ) %>" id="nav-1"><%= t('admin.brief.modulename') %></a></li>
    </ul>
  </nav>  
  <% end %>

<%= yield %>

</section>
<!--main-->
<footer _height="none"> Copyright © <a href="http://www.summers.com.tw/" target="_blank">Summers</a> </footer>
</body>
</html>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
<!--[if lt IE 9]>
<script src="js/html5.js"></script>
<![endif]-->


<meta charset="utf-8">
<meta name="Robots" content="index,follow"/>
<meta http-equiv="content-language" content="zh-TW" />

<meta property="og:url" content="<%= root_url %>"/>
<meta property="og:type" content="movie"/>

<%= render :partial => 'layouts/' + t("configs.meta") %>


<link rel="SHORTCUT ICON" href="<%= image_path("favicon.ico") %>"/>
<link rel="image_src" href="<%= image_path("thumb.jpg") %>"/>
<meta property="og:image" content="http://urbannomadfilmfest.summers.com.tw/images/thumb.jpg"/>

	<%= stylesheet_link_tag "reset", :media => "all" %>
	<%= stylesheet_link_tag "common", :media => "all" %>
	<%= stylesheet_link_tag t('configs.style'), :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-40044677-1', 'summers.com.tw');
  ga('send', 'pageview');

</script>	
</head>

<body>
<header>
  <h1><a href="http://www.urbannomad.tw" target="_blank">城市遊牧影展│URBANNOMAD FILM FEST</a></h1>
  
  <%= render :partial => "layouts/menu" %>
</header>
<section id="main">
<aside>
    <ul>      
      <li><a href="http://www.corecultural.com/" id="sp-01" target="_blank"></a></li>
      <li><a href="http://tofu.pixnet.net/blog" id="sp-02" target="_blank"></a></li>
      <li><a href="#" id="sp-03" target="_blank"></a></li>
      <li><a href="http://www.nvidia.com.tw/page/home.html" id="sp-04" target="_blank"></a></li>
      <li><a href="http://www.fuudai.com/" id="sp-05" target="_blank"></a></li>
      <li><a href="http://www.georgpeck.com/" id="sp-06" target="_blank"></a></li>
      <li><a href="http://www.foodpanda.com.tw/" id="sp-07" target="_blank"></a></li>
      <li><a href="http://www.spot-hs.org.tw/" id="sp-08" target="_blank"></a></li>
      <li><a href="http://www.huashan1914.com/" id="sp-09" target="_blank"></a></li>
      <li><a href="#" id="sp-10" target="_blank"></a></li>
      <li><a href="http://www.dfi.dk/" id="sp-11" target="_blank"></a></li>
      <li><a href="#" id="sp-12" target="_blank"></a></li>
      <li><a href="https://www.facebook.com/jimiskate" id="sp-13" target="_blank"></a></li>
      <li><a href="https://www.facebook.com/idocare.taiwan" id="sp-14" target="_blank"></a></li>
      <li><a href="#" id="sp-15" target="_blank"></a></li>
      <li><a href="#" id="sp-16" target="_blank"></a></li>
      <li><a href="http://www.summers.com.tw/" id="sp-17" target="_blank"></a></li>
      <li><a href="http://www.optoma.com.tw/home/default.aspx?" id="sp-18" target="_blank"></a></li>
      <li><a href="http://www.alleycatspizza.com/Web/Home/index.aspx" id="sp-19" target="_blank"></a></li>
      <li><a href="http://www.bessiebyer.com/" id="sp-20" target="_blank"></a></li>
      <li><a href="http://www.ntmofa.gov.tw/" id="sp-21" target="_blank"></a></li>
      <li><a href="#" id="sp-22" target="_blank"></a></li>
      <li><a href="#" id="sp-23" target="_blank"></a></li>
      <li><a href="#" id="sp-24" target="_blank"></a></li>
      <li><a href="http://www.springscream.com/" id="sp-25" target="_blank"></a></li>
      <li><a href="#" id="sp-26" target="_blank"></a></li>
      <li><a href="https://www.facebook.com/Screaming.Eyes" id="sp-27" target="_blank"></a></li>
      <li><a href="http://www.kgbburgers.com/" id="sp-28" target="_blank"></a></li>
      <li><a href="http://www.petshopsgirl.com/blog/" id="sp-29" target="_blank"></a></li>
      <li><a href="http://www.toasteriacafe.com/" id="sp-30" target="_blank"></a></li>
      <li><a href="http://www.gigguide.tw/" id="sp-31" target="_blank"></a></li>
      <li><a href="http://www.taiwanease.com/classifieds/?src=taiwanted" id="sp-32" target="_blank"></a></li>
      <li><a href="http://www.taiwanease.com/" id="sp-33" target="_blank"></a></li>
    </ul>
    <div id="summer"> <a href="http://www.summers.com.tw/" target="_blank">網頁製作由<br>
      夏天廣告贊助</a> </div>
  </aside>
  <article>
  	<%= yield %>
  </article>
</section>
<%= render :partial => "layouts/" + t("configs.footer") %>
</body>
</html>